/*
 * ---------------------------------------------------------------------------
 * File        : EntityBase.cs
 * Project     : Smart Solar Microgrid Trading System — SE4040 Assignment 1
 * Author      : <Your Full Name> (<IT Number>)
 * Created     : 2026-09-17
 * Description : Abstract base class shared by every document stored in MongoDB.
 *               Holds the identity and audit fields that all four collections
 *               need, so they are declared once rather than repeated in each
 *               entity.
 *
 * OOP         : Abstraction and inheritance. EntityBase cannot be instantiated
 *               on its own; it exists only to be specialised by User,
 *               SolarStationInfo, EnergyBookingSlot and EnergyReservation.
 * SOLID       : Liskov Substitution — every derived entity is usable wherever
 *               an EntityBase is expected, which is what allows the generic
 *               MongoRepository<TEntity> to work with all four types.
 * Design note : Id is exposed as a string rather than MongoDB's ObjectId so
 *               that the MongoDB driver's types never leak into the service or
 *               controller layers, or into the JSON the clients receive.
 * ---------------------------------------------------------------------------
 */

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SolarMicrogrid.Api.Models;

/// <summary>
/// Common identity and audit fields for all persisted documents.
/// </summary>
public abstract class EntityBase
{
    /// <summary>
    /// Unique document identifier, generated by MongoDB on insert.
    /// Null until the entity has been saved for the first time.
    /// </summary>
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    [BsonElement("_id")]
    public string? Id { get; set; }

    /// <summary>
    /// UTC timestamp of when the document was first created.
    /// Stored in UTC so the 7 day and 12 hour booking rules compare correctly
    /// regardless of the time zone of the machine running the service.
    /// </summary>
    [BsonElement("createdAt")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the most recent change to the document.</summary>
    [BsonElement("updatedAt")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
